version: "3.11"

services:
  # rosen_frontend:
  #   container_name: docker-rosen-front-c
  #   image: docker-rosen-front-i
  #   build:
  #     context: .
  #     dockerfile: rosen_frontend/Dockerfile
  #   volumes:
  #     - ./rosen_frontend:/src
  #     - /src/node_modules
  #     - /src/.next
  #   ports:
  #     - 3000:3000
  backend:
    container_name: docker-backend-cname
    image: docker-backend-image
    build:
      context: .
      dockerfile: backend/Dockerfile
    volumes:
      - ./backend
    ports:
      - "8000:8000"
    # depends_on:
    #   - db
  # db:
  #   image: postgres
  #   volumes:
  #     - ./postgres/database:/var/lib/postgresql/data
  #   environment:
  #     - POSTGRES_DB=postgres
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=postgres
  #   ports:
  #     - "5432:5432"