version: "3.11"

services:
  frontend:
    container_name: docker-frontend-cname
    image: docker-frontend-image
    build:
      context: .
      dockerfile: frontend/Dockerfile
    volumes:
      - ./frontend:/src
      - /src/node_modules
      - /src/.next
    ports:
      - 3000:3000
  backend:
    container_name: docker-backend-cname
    image: docker-backend-image
    build:
      context: .
      dockerfile: backend/Dockerfile
    volumes:
      - ./backend:/backend
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: postgres
    volumes:
      - ./postgres/database:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=renoCalcDB
      - POSTGRES_USER=postgresReno
      - POSTGRES_PASSWORD=postgresReno
    ports:
      - "5432:5432"