# Generated by Django 4.2.6 on 2023-10-22 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContractorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phoneNumber', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=100)),
                ('website_link', models.URLField(blank=True, null=True)),
                ('rating', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyTypeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='RegionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phoneNumber', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserHomeAndRenovationConfigurationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniqueConfiguration', models.JSONField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='renoCalc.usermodel')),
            ],
        ),
        migrations.CreateModel(
            name='SurveyorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('commission', models.JSONField()),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='renoCalc.contractormodel')),
            ],
        ),
        migrations.CreateModel(
            name='RealEstateLaywerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('commission', models.JSONField()),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='renoCalc.contractormodel')),
            ],
        ),
        migrations.CreateModel(
            name='RealEstateAgentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('commission', models.JSONField()),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='renoCalc.contractormodel')),
                ('regions', models.ManyToManyField(to='renoCalc.regionmodel')),
                ('typeOfWork', models.ManyToManyField(to='renoCalc.propertytypemodel')),
            ],
        ),
        migrations.CreateModel(
            name='MortgageBrokerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('financeMinimum', models.IntegerField()),
                ('commission', models.JSONField()),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='renoCalc.contractormodel')),
            ],
        ),
        migrations.CreateModel(
            name='LaundryAppliances',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=100)),
                ('choice', models.CharField(max_length=100)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='renoCalc.contractormodel')),
            ],
        ),
        migrations.CreateModel(
            name='HomeInspectorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('commission', models.JSONField()),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='renoCalc.contractormodel')),
            ],
        ),
        migrations.CreateModel(
            name='ArchitectModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('commission', models.JSONField()),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='renoCalc.contractormodel')),
            ],
        ),
    ]
