# Generated by Django 4.2.6 on 2023-10-26 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renoCalc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
