# Generated by Django 4.2.6 on 2023-10-16 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renoCalc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractor',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True),
        ),
    ]
