# Generated by Django 4.2.6 on 2023-10-27 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('renoCalc', '0002_alter_usermodel_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='username',
        ),
    ]
