# Generated by Django 4.2.6 on 2023-10-20 02:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('renoCalc', '0007_architect'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contractor',
            new_name='ContractorModel',
        ),
        migrations.RenameModel(
            old_name='User',
            new_name='UserModel',
        ),
        migrations.CreateModel(
            name='UserHomeAndRenovationConfigurationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniqueConfiguration', models.JSONField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='renoCalc.usermodel')),
            ],
        ),
    ]
