# Generated by Django 4.2.6 on 2023-10-20 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('renoCalc', '0008_rename_contractor_contractormodel_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HomeInspector',
            new_name='ArchitectModel',
        ),
        migrations.RenameModel(
            old_name='Architect',
            new_name='HomeInspectorModel',
        ),
        migrations.RenameModel(
            old_name='MortgageBroker',
            new_name='MortgageBrokerModel',
        ),
        migrations.RenameModel(
            old_name='RealEstateAgent',
            new_name='RealEstateAgentModel',
        ),
        migrations.RenameModel(
            old_name='Surveyor',
            new_name='RealEstateLaywerModel',
        ),
        migrations.RenameModel(
            old_name='RealEstateLaywer',
            new_name='SurveyorModel',
        ),
    ]
