name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps: 
    - name: Checkout
      uses: actions/checkout@v3
    - name: Build and Run the Docker Containers
      uses: isbang/compose-action@v1.4.1
      with:
        compose-file: "./docker-compose.yaml"
        up-flags: "--build"
