name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps: 
    - name: Checkout
      uses: actions/checkout@v3
    # - name: Install Python Dependencies
    #   run: pip install -r backend/requirements.txt
    # - name: Run Django Unit Tests
    #   run: python backend/manage.py test backend/
    - uses: isbang/compose-action@v1.4.1
      with:
        compose-file: "./docker-compose.yaml"
        up-flags: "--build"
